### ISSUE TITLE
Killing assisirun.py messes up the console

### ISSUE THREAD

**Issue by dmiklic** [assisi/assisipy#49]
LInefeed characters are not rendered properly any more, after stopping assisirun.py with Ctrl-C. Temporary workaround:

just issue the `reset` command from the terminal.

**Comment by rmm-fcul** [comment]
The NL/LF character gets broken in some cases even if the target code completed ok, when there are multiple targets (including >1 casu on a single simulated host).  As noted, `reset` restores in this situation too

**Comment by rmm-fcul** [comment]
After investigating what changes before and after running `assisirun.py`, I *think* that the problem is to do with the echo setting, within tty.  But the two that are consistently changed seem to be `-echo -icanon`

Using stty sane means:

> Same as cread -ignbrk brkint -inlcr -igncr icrnl -iutf8 -ixoff -iuclc -ixany imaxbel opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0 isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke, all special characters to their default values.

[docs](https://www.systutorials.com/docs/linux/man/1-stty/)
